# Generated by Django 3.0.1 on 2019-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
