# Generated by Django 3.0.1 on 2019-12-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJangoApp', '0003_auto_20191223_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='nrDitesh',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
