# Generated by Django 3.0.1 on 2019-12-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJangoApp', '0004_tours_nrditesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='tel',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
