# Generated by Django 3.0.1 on 2019-12-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJangoApp', '0005_kontakt_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavTours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pershkrim', models.CharField(max_length=300)),
                ('dataNisjes', models.CharField(max_length=30)),
                ('dataKthimit', models.CharField(max_length=30)),
                ('cmimi', models.CharField(max_length=30)),
                ('nrDitesh', models.CharField(max_length=30)),
                ('foto', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
