# Generated by Django 3.0.1 on 2020-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJangoApp', '0006_favtours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakt',
            name='tour',
        ),
        migrations.AddField(
            model_name='kontakt',
            name='select',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
