# Generated by Django 3.0.1 on 2020-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJangoApp', '0007_auto_20200106_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
